# 修改安装依赖这一步
      - name: Install Dependencies
        run: |
          pip install playwright requests
          playwright install chromium # 安装浏览器内核

      # 运行步骤不用变，还是 python glados.py
      - name: Start Checkin
        env:
          GLADOS_COOKIE: ${{ secrets.GLADOS_COOKIE }}
        run: python glados.py
